# Generated by Django 4.1.6 on 2023-02-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab7_django', '0003_rename_posttags_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='uadmin',
            field=models.BooleanField(default=False, verbose_name='Администратор?'),
        ),
    ]
