# Generated by Django 4.1.6 on 2023-02-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab7_django', '0004_users_uadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.TextField(default='P@ssw0rd!', verbose_name='Пароль'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='password_confirm',
            field=models.TextField(default='P@ssw0rd!', verbose_name='Пароль еще раз'),
            preserve_default=False,
        ),
    ]
