# Generated by Django 4.1.6 on 2023-02-05 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab7_django', '0002_alter_rating_likes_sum'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostTags',
            new_name='Tags',
        ),
    ]
