# Generated by Django 4.1.6 on 2023-02-06 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab7_django', '0005_users_password_users_password_confirm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='password',
            new_name='password1',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='password_confirm',
            new_name='password2',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='nickname',
            new_name='username',
        ),
    ]
