# Generated by Django 4.1.6 on 2023-02-14 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab7_django', '0006_rename_password_users_password1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='likes_cnt',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='post',
        ),
        migrations.AlterField(
            model_name='rating',
            name='nickname',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='lab7_django.users', verbose_name='Никнейм'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab7_django.post', verbose_name='Идентификатор поста'),
        ),
        migrations.AddField(
            model_name='likes',
            name='post',
            field=models.ManyToManyField(to='lab7_django.post'),
        ),
    ]
